### ISSUE TITLE
Doesn't build for 32bit architecture

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dj64dev#7]
I get this:
```
cc -E -I . -I ../../../../include -DDJ64 -D_IN_DJ64 -CC -g0 -MD doprnt.c | \
  sed -E -e 's/^\*\/#/\*\/\n#/' -e 's/^\*\/ *;/\*\/\n;\n/' | \
  cc @../../../gcc.opt -I ../../../../include  -xc - -c  -o doprnt.o
doprnt.c: In function ‘_doprnt’:
doprnt.c:342:14: error: ‘to_be_printed’ may be used uninitialized [-Werror=maybe-uninitialized]
  342 |         argp = to_be_printed;
      |         ~~~~~^~~~~~~~~~~~~~~
doprnt.c:144:11: note: ‘to_be_printed’ was declared here
  144 |   va_list to_be_printed;             /* argument to be printed if numeric specifier are used */
      |           ^~~~~~~~~~~~~
At top level:
cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-unneeded-internal-declaration’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
```

GCC info:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/12/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 12.2.0-14' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=i686-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14)
```

**Comment by stsp** [comment]
Should now be fixed, although I
believe this is a gcc bug, or a too
small optimization level.

**Comment by jschwartzenberg** [comment]
GCC is still not happy I'm afraid:
```
cc -E -I . -I ../../../../include -DDJ64 -D_IN_DJ64 -CC -g0 -MD doprnt.c | \
  sed -E -e 's/^\*\/#/\*\/\n#/' -e 's/^\*\/ *;/\*\/\n;\n/' | \
  cc @../../../gcc.opt -I ../../../../include  -xc - -c  -o doprnt.o
doprnt.c: In function ‘_doprnt’:
doprnt.c:144:27: error: empty scalar initializer
  144 |   va_list to_be_printed = {};        /* argument to be printed if numeric specifier are used */
      |                           ^
doprnt.c:144:27: note: (near initialization for ‘to_be_printed’)
At top level:
cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-unneeded-internal-declaration’ may have been intended to silence earlier diagnostics
```

**Comment by stsp** [comment]
Wow.
Does it help to use `{0}` there?

**Comment by jschwartzenberg** [comment]
Yep, now it continues.

**Comment by jschwartzenberg** [comment]
Trips over another error now:
```
./thunk_asms.h:143:9: error: conflicting types for ‘__dpmi_allocate_real_mode_callback’; have ‘int32_t(uint32_t,  uint32_t,  __dpmi_raddr *)’ {aka ‘int(unsigned int,  unsigned int,  __dpmi_raddr *)’}
  143 | _THUNK3(9, __ARG(DWORD), __RET, __dpmi_allocate_real_mode_callback, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG_PTR(__dpmi_raddr), , __ARG_PTR_A(__dpmi_raddr), __ARG_PTR_A(__dpmi_raddr), __CNV_PTR, _L_SZ(3), _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thunk_incs.h:3,
                 from thunks_p.c:1:
../../../include/dpmi.h:193:9: note: previous declaration of ‘__dpmi_allocate_real_mode_callback’ with type ‘int(long unsigned int,  long unsigned int,  __dpmi_raddr *)’
  193 | int     __dpmi_allocate_real_mode_callback(ULONG32 _handler, ULONG32 _regs, __dpmi_raddr *_ret); /* DPMI 0.9 AX=0303 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:146:9: error: conflicting types for ‘__dpmi_clear_debug_watchpoint’; have ‘int32_t(uint32_t)’ {aka ‘int(unsigned int)’}
  146 | _THUNK1(12, __ARG(DWORD), __RET, __dpmi_clear_debug_watchpoint, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:237:9: note: previous declaration of ‘__dpmi_clear_debug_watchpoint’ with type ‘int(long unsigned int)’
  237 | int     __dpmi_clear_debug_watchpoint(ULONG32 _handle);                                 /* DPMI 0.9 AX=0b01 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:151:9: error: conflicting types for ‘__dpmi_free_memory’; have ‘int32_t(uint32_t)’ {aka ‘int(unsigned int)’}
  151 | _THUNK1(17, __ARG(DWORD), __RET, __dpmi_free_memory, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:204:9: note: previous declaration of ‘__dpmi_free_memory’ with type ‘int(long unsigned int)’
  204 | int     __dpmi_free_memory(ULONG32 _handle);                                            /* DPMI 0.9 AX=0502 */
      |         ^~~~~~~~~~~~~~~~~~
./thunk_asms.h:154:9: error: conflicting types for ‘__dpmi_free_serialization_on_shared_memory’; have ‘int32_t(uint32_t,  int32_t)’ {aka int(unsigned int,  int)’}
  154 | _THUNK2(20, __ARG(DWORD), __RET, __dpmi_free_serialization_on_shared_memory, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(DWORD), , __ARG_A(DWORD), __ARG_A(DWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:247:9: note: previous declaration of ‘__dpmi_free_serialization_on_shared_memory’ with type ‘int(long unsigned int,  int)’
  247 | int     __dpmi_free_serialization_on_shared_memory(ULONG32 _handle, int _flags);                /* DPMI 1.0 AX=0d03 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:155:9: error: conflicting types for ‘__dpmi_free_shared_memory’; have ‘int32_t(uint32_t)’ {aka ‘int(unsigned int)’}
  155 | _THUNK1(21, __ARG(DWORD), __RET, __dpmi_free_shared_memory, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NO
etc. (many conflicting types)
```

**Comment by stsp** [comment]
Since the code is already full of `= {};`
stuff, I instead added `-std=c2x` in a hope
to enable that.
Needs `make clean` before testing.

**Comment by stsp** [comment]
Are you compiling for 32bit or what?

**Comment by jschwartzenberg** [comment]
Yes, this is a 32-bit system.

**Comment by stsp** [comment]
Well, there is a djgpp for 32bit systems, so
using dj64dev is plain crazy.
But I'll look at what can be done.

**Comment by stsp** [comment]
I asked at gcc bugzilla, and first of all
we need gcc-13.

**Comment by stsp** [comment]
Should now work.

**Comment by jschwartzenberg** [comment]
There are still missing types, I'll try to post the full output:
```
cc -E -I . -I ../../../include -DDJ64 -D_IN_DJ64 -I ../../djdev64/include -CC -g0 -MD thunks_p.c | \
  sed -E -e 's/^\*\/#/\*\/\n#/' -e 's/^\*\/ *;/\*\/\n;\n/' | \
  cc @../../gcc.opt  -xc - -c  -o thunks_p.o
In file included from ../../../include/dj64/thunks_p.inc:88,
                 from thunks_p.c:2:
./thunk_asms.h:143:9: error: conflicting types for â__dpmi_allocate_real_mode_callbackâ; have âint32_t(uint32_t,  uint32_t,  __dpmi_raddr *)â {aka âint(unsigned int,  unsigned int,  __dpmi_raddr *)â}
  143 | _THUNK3(9, __ARG(DWORD), __RET, __dpmi_allocate_real_mode_callback, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG_PTR(__dpmi_raddr), , __ARG_PTR_A(__dpmi_raddr), __ARG_PTR_A(__dpmi_raddr), __CNV_PTR, _L_SZ(3), _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from thunk_incs.h:3,
                 from thunks_p.c:1:
../../../include/dpmi.h:193:9: note: previous declaration of â__dpmi_allocate_real_mode_callbackâ with type âint(long unsigned int,  long unsigned int,  __dpmi_raddr *)â
  193 | int     __dpmi_allocate_real_mode_callback(ULONG32 _handler, ULONG32 _regs, __dpmi_raddr *_ret); /* DPMI 0.9 AX=0303 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:146:9: error: conflicting types for â__dpmi_clear_debug_watchpointâ; have âint32_t(uint32_t)â {aka âint(unsigned int)â}
  146 | _THUNK1(12, __ARG(DWORD), __RET, __dpmi_clear_debug_watchpoint, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:237:9: note: previous declaration of â__dpmi_clear_debug_watchpointâ with type âint(long unsigned int)â
  237 | int     __dpmi_clear_debug_watchpoint(ULONG32 _handle);                                 /* DPMI 0.9 AX=0b01 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:151:9: error: conflicting types for â__dpmi_free_memoryâ; have âint32_t(uint32_t)â {aka âint(unsigned int)â}
  151 | _THUNK1(17, __ARG(DWORD), __RET, __dpmi_free_memory, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:204:9: note: previous declaration of â__dpmi_free_memoryâ with type âint(long unsigned int)â
  204 | int     __dpmi_free_memory(ULONG32 _handle);                                            /* DPMI 0.9 AX=0502 */
      |         ^~~~~~~~~~~~~~~~~~
./thunk_asms.h:154:9: error: conflicting types for â__dpmi_free_serialization_on_shared_memoryâ; have âint32_t(uint32_t,  int32_t)â {aka âint(unsigned int,  int)â}
  154 | _THUNK2(20, __ARG(DWORD), __RET, __dpmi_free_serialization_on_shared_memory, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(DWORD), , __ARG_A(DWORD), __ARG_A(DWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:247:9: note: previous declaration of â__dpmi_free_serialization_on_shared_memoryâ with type âint(long unsigned int,  int)â
  247 | int     __dpmi_free_serialization_on_shared_memory(ULONG32 _handle, int _flags);                /* DPMI 1.0 AX=0d03 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:155:9: error: conflicting types for â__dpmi_free_shared_memoryâ; have âint32_t(uint32_t)â {aka âint(unsigned int)â}
  155 | _THUNK1(21, __ARG(DWORD), __RET, __dpmi_free_shared_memory, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:245:9: note: previous declaration of â__dpmi_free_shared_memoryâ with type âint(long unsigned int)â
  245 | int     __dpmi_free_shared_memory(ULONG32 _handle);                                     /* DPMI 1.0 AX=0d01 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:170:9: error: conflicting types for â__dpmi_get_page_sizeâ; have âint32_t(uint32_t *)â {aka âint(unsigned int *)â}
  170 | _THUNK1(36, __ARG(DWORD), __RET, __dpmi_get_page_size, __ARG_PTR(UDWORD), , __ARG_PTR_A(UDWORD), __ARG_PTR_A(UDWORD), __CNV_OPTR, _L_SZ(1), _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:220:9: note: previous declaration of â__dpmi_get_page_sizeâ with type âint(long unsigned int *)â
  220 | int     __dpmi_get_page_size(__out ULONG32 *_size);                                             /* DPMI 0.9 AX=0604 */
      |         ^~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:175:9: error: conflicting types for â__dpmi_get_segment_base_addressâ; have âint32_t(int32_t,  uint32_t *)â {aka âint(int,  unsigned int *)â}
  175 | _THUNK2(41, __ARG(DWORD), __RET, __dpmi_get_segment_base_address, __ARG(DWORD), , __ARG_A(DWORD), __ARG_A(DWORD), __CNV_SIMPLE, _L_NONE, __ARG_PTR(UDWORD), , __ARG_PTR_A(UDWORD), __ARG_PTR_A(UDWORD), __CNV_OPTR, _L_SZ(2), _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:156:9: note: previous declaration of â__dpmi_get_segment_base_addressâ with type âint(int,  long unsigned int *)â
  156 | int     __dpmi_get_segment_base_address(int _selector, __out ULONG32 *_addr);                   /* DPMI 0.9 AX=0006 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:176:10: error: conflicting types for â__dpmi_get_segment_limitâ; have âuint32_t(int32_t)â {aka âunsigned int(int)â}
  176 | _THUNK1(42, __ARG(UDWORD), __RET, __dpmi_get_segment_limit, __ARG(DWORD), , __ARG_A(DWORD), __ARG_A(DWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:158:15: note: previous declaration of â__dpmi_get_segment_limitâ with type âlong unsigned int(int)â
  158 | ULONG32 __dpmi_get_segment_limit(int _selector);                                                /* LSL instruction  */
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:178:9: error: conflicting types for â__dpmi_get_state_of_debug_watchpointâ; have âint32_t(uint32_t,  int32_t *)â {aka âint(unsigned int,  int *)â}
  178 | _THUNK2(44, __ARG(DWORD), __RET, __dpmi_get_state_of_debug_watchpoint, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG_PTR(DWORD), , __ARG_PTR_A(DWORD), __ARG_PTR_A(DWORD), __CNV_OPTR, _L_SZ(2), _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:238:9: note: previous declaration of â__dpmi_get_state_of_debug_watchpointâ with type âint(long unsigned int,  int *)â
  238 | int     __dpmi_get_state_of_debug_watchpoint(ULONG32 _handle, __out int *_status);              /* DPMI 0.9 AX=0b02 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:186:9: error: conflicting types for â__dpmi_map_conventional_memory_in_memory_blockâ; have âint32_t(__dpmi_meminfo *, uint32_t)â {aka âint(__dpmi_meminfo *, unsigned int)â}
  186 | _THUNK2(52, __ARG(DWORD), __RET, __dpmi_map_conventional_memory_in_memory_block, __ARG_PTR(__dpmi_meminfo), , __ARG_PTR_A(__dpmi_meminfo), __ARG_PTR_A(__dpmi_meminfo), __CNV_PTR, _L_SZ(1), __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:212:9: note: previous declaration of â__dpmi_map_conventional_memory_in_memory_blockâ with type âint(__dpmi_meminfo *, long unsigned int)â
  212 | int     __dpmi_map_conventional_memory_in_memory_block(__dpmi_meminfo *_info, ULONG32 _linaddr); /* DPMI 1.0 AX=0509 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:187:9: error: conflicting types for â__dpmi_map_device_in_memory_blockâ; have âint32_t(__dpmi_meminfo *, uint32_t)â {aka âint(__dpmi_meminfo *, unsigned int)â}
  187 | _THUNK2(53, __ARG(DWORD), __RET, __dpmi_map_device_in_memory_block, __ARG_PTR(__dpmi_meminfo), , __ARG_PTR_A(__dpmi_meminfo), __ARG_PTR_A(__dpmi_meminfo), __CNV_PTR, _L_SZ(1), __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:211:9: note: previous declaration of â__dpmi_map_device_in_memory_blockâ with type âint(__dpmi_meminfo *, long unsigned int)â
  211 | int     __dpmi_map_device_in_memory_block(__dpmi_meminfo *_info, ULONG32 _physaddr);    /* DPMI 1.0 AX=0508 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:192:9: error: conflicting types for â__dpmi_reset_debug_watchpointâ; have âint32_t(uint32_t)â {aka âint(unsigned int)â}
  192 | _THUNK1(58, __ARG(DWORD), __RET, __dpmi_reset_debug_watchpoint, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:239:9: note: previous declaration of â__dpmi_reset_debug_watchpointâ with type âint(long unsigned int)â
  239 | int     __dpmi_reset_debug_watchpoint(ULONG32 _handle);                                 /* DPMI 0.9 AX=0b03 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:197:9: error: conflicting types for â__dpmi_serialize_on_shared_memoryâ; have âint32_t(uint32_t,  int32_t)â {aka âint(unsigned int,  int)â}
  197 | _THUNK2(63, __ARG(DWORD), __RET, __dpmi_serialize_on_shared_memory, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(DWORD), , __ARG_A(DWORD), __ARG_A(DWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:246:9: note: previous declaration of â__dpmi_serialize_on_shared_memoryâ with type âint(long unsigned int,  int)â
  246 | int     __dpmi_serialize_on_shared_memory(ULONG32 _handle, int _flags);                 /* DPMI 1.0 AX=0d02 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:209:9: error: conflicting types for â__dpmi_set_segment_base_addressâ; have âint32_t(int32_t,  uint32_t)â {aka âint(int,  unsigned int)â}
  209 | _THUNK2(75, __ARG(DWORD), __RET, __dpmi_set_segment_base_address, __ARG(DWORD), , __ARG_A(DWORD), __ARG_A(DWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:157:9: note: previous declaration of â__dpmi_set_segment_base_addressâ with type âint(int,  long unsigned int)â
  157 | int     __dpmi_set_segment_base_address(int _selector, ULONG32 _address);                       /* DPMI 0.9 AX=0007 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:210:9: error: conflicting types for â__dpmi_set_segment_limitâ; have âint32_t(int32_t,  uint32_t)â {aka âint(int,  unsigned int)â}
  210 | _THUNK2(76, __ARG(DWORD), __RET, __dpmi_set_segment_limit, __ARG(DWORD), , __ARG_A(DWORD), __ARG_A(DWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
../../../include/dpmi.h:159:9: note: previous declaration of â__dpmi_set_segment_limitâ with type âint(int,  long unsigned int)â
  159 | int     __dpmi_set_segment_limit(int _selector, ULONG32 _limit);                                /* DPMI 0.9 AX=0008 */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./thunk_asms.h:220:9: error: conflicting types for â_farnspeekbâ; have âuint8_t(uint32_t)â {aka âunsigned char(unsigned int)â}
  220 | _THUNK1(86, __ARG(UBYTE), __RET, _farnspeekb, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~
In file included from thunk_incs.h:13:
../../../include/sys/farptr.h:85:15: note: previous declaration of â_farnspeekbâ with type âunsigned char(long unsigned int)â
   85 | unsigned char _farnspeekb(ULONG32);
      |               ^~~~~~~~~~~
./thunk_asms.h:221:9: error: conflicting types for â_farnspeekb_gsâ; have âuint8_t(uint32_t)â {aka âunsigned char(unsigned int)â}
  221 | _THUNK1(87, __ARG(UBYTE), __RET, _farnspeekb_gs, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~~~
In file included from thunk_incs.h:7:
../../../include/libc/farptrgs.h:87:15: note: previous declaration of â_farnspeekb_gsâ with type âunsigned char(long unsigned int)â
   87 | unsigned char _farnspeekb_gs(ULONG32);
      |               ^~~~~~~~~~~~~~
./thunk_asms.h:222:10: error: conflicting types for â_farnspeeklâ; have âuint32_t(uint32_t)â {aka âunsigned int(unsigned int)â}
  222 | _THUNK1(88, __ARG(UDWORD), __RET, _farnspeekl, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~~~
../../../include/sys/farptr.h:87:15: note: previous declaration of â_farnspeeklâ with type âlong unsigned int(long unsigned int)â
   87 | ULONG32 _farnspeekl(ULONG32);
      |               ^~~~~~~~~~~
./thunk_asms.h:223:10: error: conflicting types for â_farnspeekl_gsâ; have âuint32_t(uint32_t)â {aka âunsigned int(unsigned int)â}
  223 | _THUNK1(89, __ARG(UDWORD), __RET, _farnspeekl_gs, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~~~~~~
../../../include/libc/farptrgs.h:89:15: note: previous declaration of â_farnspeekl_gsâ with type âlong unsigned int(long unsigned int)â
   89 | ULONG32 _farnspeekl_gs(ULONG32);
      |               ^~~~~~~~~~~~~~
./thunk_asms.h:224:10: error: conflicting types for â_farnspeekwâ; have âuint16_t(uint32_t)â {aka âshort unsigned int(unsigned int)â}
  224 | _THUNK1(90, __ARG(UWORD), __RET, _farnspeekw, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~~~
../../../include/sys/farptr.h:86:16: note: previous declaration of â_farnspeekwâ with type âshort unsigned int(long unsigned int)â
   86 | unsigned short _farnspeekw(ULONG32);
      |                ^~~~~~~~~~~
./thunk_asms.h:225:10: error: conflicting types for â_farnspeekw_gsâ; have âuint16_t(uint32_t)â {aka âshort unsigned int(unsigned int)â}
  225 | _THUNK1(91, __ARG(UWORD), __RET, _farnspeekw_gs, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~~~~~~
../../../include/libc/farptrgs.h:88:16: note: previous declaration of â_farnspeekw_gsâ with type âshort unsigned int(long unsigned int)â
   88 | unsigned short _farnspeekw_gs(ULONG32);
      |                ^~~~~~~~~~~~~~
./thunk_asms.h:226:6: error: conflicting types for â_farnspokebâ; have âvoid(uint32_t,  uint8_t)â {aka âvoid(unsigned int,  unsigned char)â}
  226 | _THUNK2_v(92, _farnspokeb, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UBYTE), , __ARG_A(UBYTE), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~
../../../include/sys/farptr.h:82:6: note: previous declaration of â_farnspokebâ with type âvoid(long unsigned int,  unsigned char)â
   82 | void _farnspokeb(ULONG32, unsigned char);
      |      ^~~~~~~~~~~
./thunk_asms.h:227:6: error: conflicting types for â_farnspokeb_gsâ; have âvoid(uint32_t,  uint8_t)â {aka âvoid(unsigned int,  unsigned char)â}
  227 | _THUNK2_v(93, _farnspokeb_gs, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UBYTE), , __ARG_A(UBYTE), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~~~~
../../../include/libc/farptrgs.h:84:6: note: previous declaration of â_farnspokeb_gsâ with type âvoid(long unsigned int,  unsigned char)â
   84 | void _farnspokeb_gs(ULONG32, unsigned char);
      |      ^~~~~~~~~~~~~~
./thunk_asms.h:228:6: error: conflicting types for â_farnspokelâ; have âvoid(uint32_t,  uint32_t)â {aka âvoid(unsigned int,  unsigned int)â}
  228 | _THUNK2_v(94, _farnspokel, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~
../../../include/sys/farptr.h:84:6: note: previous declaration of â_farnspokelâ with type âvoid(long unsigned int,  long unsigned int)â
   84 | void _farnspokel(ULONG32, ULONG32);
      |      ^~~~~~~~~~~
./thunk_asms.h:229:6: error: conflicting types for â_farnspokel_gsâ; have âvoid(uint32_t,  uint32_t)â {aka âvoid(unsigned int,  unsigned int)â}
  229 | _THUNK2_v(95, _farnspokel_gs, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~~~~
../../../include/libc/farptrgs.h:86:6: note: previous declaration of â_farnspokel_gsâ with type âvoid(long unsigned int,  long unsigned int)â
   86 | void _farnspokel_gs(ULONG32, ULONG32);
      |      ^~~~~~~~~~~~~~
./thunk_asms.h:230:6: error: conflicting types for â_farnspokewâ; have âvoid(uint32_t,  uint16_t)â {aka âvoid(unsigned int,  short unsigned int)â}
  230 | _THUNK2_v(96, _farnspokew, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~
../../../include/sys/farptr.h:83:6: note: previous declaration of â_farnspokewâ with type âvoid(long unsigned int,  short unsigned int)â
   83 | void _farnspokew(ULONG32, unsigned short);
      |      ^~~~~~~~~~~
./thunk_asms.h:231:6: error: conflicting types for â_farnspokew_gsâ; have âvoid(uint32_t,  uint16_t)â {aka âvoid(unsigned int,  short unsigned int)â}
  231 | _THUNK2_v(97, _farnspokew_gs, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~~~~
../../../include/libc/farptrgs.h:85:6: note: previous declaration of â_farnspokew_gsâ with type âvoid(long unsigned int,  short unsigned int)â
   85 | void _farnspokew_gs(ULONG32, unsigned short);
      |      ^~~~~~~~~~~~~~
./thunk_asms.h:232:9: error: conflicting types for â_farpeekbâ; have âuint8_t(uint16_t,  uint32_t)â {aka âunsigned char(short unsigned int,  unsigned int)â}
  232 | _THUNK2(98, __ARG(UBYTE), __RET, _farpeekb, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~
../../../include/sys/farptr.h:77:15: note: previous declaration of â_farpeekbâ with type âunsigned char(short unsigned int,  long unsigned int)â
   77 | unsigned char _farpeekb(unsigned short, ULONG32);
      |               ^~~~~~~~~
./thunk_asms.h:233:9: error: conflicting types for â_farpeekb_gsâ; have âuint8_t(uint16_t,  uint32_t)â {aka âunsigned char(short unsigned int,  unsigned int)â}
  233 | _THUNK2(99, __ARG(UBYTE), __RET, _farpeekb_gs, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |         ^~~~~~~~~~~~
../../../include/libc/farptrgs.h:79:15: note: previous declaration of â_farpeekb_gsâ with type âunsigned char(short unsigned int,  long unsigned int)â
   79 | unsigned char _farpeekb_gs(unsigned short, ULONG32);
      |               ^~~~~~~~~~~~
./thunk_asms.h:234:10: error: conflicting types for â_farpeeklâ; have âuint32_t(uint16_t,  uint32_t)â {aka âunsigned int(short unsigned int,  unsigned int)â}
  234 | _THUNK2(100, __ARG(UDWORD), __RET, _farpeekl, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~
../../../include/sys/farptr.h:79:15: note: previous declaration of â_farpeeklâ with type âlong unsigned int(short unsigned int,  long unsigned int)â
   79 | ULONG32 _farpeekl(unsigned short, ULONG32);
      |               ^~~~~~~~~
./thunk_asms.h:235:10: error: conflicting types for â_farpeekl_gsâ; have âuint32_t(uint16_t,  uint32_t)â {aka âunsigned int(short unsigned int,  unsigned int)â}
  235 | _THUNK2(101, __ARG(UDWORD), __RET, _farpeekl_gs, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~~~~
../../../include/libc/farptrgs.h:81:15: note: previous declaration of â_farpeekl_gsâ with type âlong unsigned int(short unsigned int,  long unsigned int)â
   81 | ULONG32 _farpeekl_gs(unsigned short, ULONG32);
      |               ^~~~~~~~~~~~
./thunk_asms.h:236:10: error: conflicting types for â_farpeekwâ; have âuint16_t(uint16_t,  uint32_t)â {aka âshort unsigned int(short unsigned int,  unsigned int)â}
  236 | _THUNK2(102, __ARG(UWORD), __RET, _farpeekw, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~
../../../include/sys/farptr.h:78:16: note: previous declaration of â_farpeekwâ with type âshort unsigned int(short unsigned int,  long unsigned int)â
   78 | unsigned short _farpeekw(unsigned short, ULONG32);
      |                ^~~~~~~~~
./thunk_asms.h:237:10: error: conflicting types for â_farpeekw_gsâ; have âuint16_t(uint16_t,  uint32_t)â {aka âshort unsigned int(short unsigned int,  unsigned int)â}
  237 | _THUNK2(103, __ARG(UWORD), __RET, _farpeekw_gs, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |          ^~~~~~~~~~~~
../../../include/libc/farptrgs.h:80:16: note: previous declaration of â_farpeekw_gsâ with type âshort unsigned int(short unsigned int,  long unsigned int)â
   80 | unsigned short _farpeekw_gs(unsigned short, ULONG32);
      |                ^~~~~~~~~~~~
./thunk_asms.h:238:6: error: conflicting types for â_farpokebâ; have âvoid(uint16_t,  uint32_t,  uint8_t)â {aka âvoid(short unsigned int,  unsigned int,  unsigned char)â}
  238 | _THUNK3_v(104, _farpokeb, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UBYTE), , __ARG_A(UBYTE), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~
../../../include/sys/farptr.h:74:6: note: previous declaration of â_farpokebâ with type âvoid(short unsigned int,  long unsigned int,  unsigned char)â
   74 | void _farpokeb(unsigned short, ULONG32, unsigned char);
      |      ^~~~~~~~~
./thunk_asms.h:239:6: error: conflicting types for â_farpokeb_gsâ; have âvoid(uint16_t,  uint32_t,  uint8_t)â {aka âvoid(short unsigned int,  unsigned int,  unsigned char)â}
  239 | _THUNK3_v(105, _farpokeb_gs, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UBYTE), , __ARG_A(UBYTE), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~~
../../../include/libc/farptrgs.h:76:6: note: previous declaration of â_farpokeb_gsâ with type âvoid(short unsigned int,  long unsigned int,  unsigned char)â
   76 | void _farpokeb_gs(unsigned short, ULONG32, unsigned char);
      |      ^~~~~~~~~~~~
./thunk_asms.h:240:6: error: conflicting types for â_farpokelâ; have âvoid(uint16_t,  uint32_t,  uint32_t)â {aka âvoid(short unsigned int,  unsigned int,  unsigned int)â}
  240 | _THUNK3_v(106, _farpokel, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~
../../../include/sys/farptr.h:76:6: note: previous declaration of â_farpokelâ with type âvoid(short unsigned int,  long unsigned int,  long unsigned int)â
   76 | void _farpokel(unsigned short, ULONG32, ULONG32);
      |      ^~~~~~~~~
./thunk_asms.h:241:6: error: conflicting types for â_farpokel_gsâ; have âvoid(uint16_t,  uint32_t,  uint32_t)â {aka âvoid(short unsigned int,  unsigned int,  unsigned int)â}
  241 | _THUNK3_v(107, _farpokel_gs, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~~
../../../include/libc/farptrgs.h:78:6: note: previous declaration of â_farpokel_gsâ with type âvoid(short unsigned int,  long unsigned int,  long unsigned int)â
   78 | void _farpokel_gs(unsigned short, ULONG32, ULONG32);
      |      ^~~~~~~~~~~~
./thunk_asms.h:242:6: error: conflicting types for â_farpokewâ; have âvoid(uint16_t,  uint32_t,  uint16_t)â {aka âvoid(short unsigned int,  unsigned int,  short unsigned int)â}
  242 | _THUNK3_v(108, _farpokew, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~
../../../include/sys/farptr.h:75:6: note: previous declaration of â_farpokewâ with type âvoid(short unsigned int,  long unsigned int,  short unsigned int)â
   75 | void _farpokew(unsigned short, ULONG32, unsigned short);
      |      ^~~~~~~~~
./thunk_asms.h:243:6: error: conflicting types for â_farpokew_gsâ; have âvoid(uint16_t,  uint32_t,  uint16_t)â {aka âvoid(short unsigned int,  unsigned int,  short unsigned int)â}
  243 | _THUNK3_v(109, _farpokew_gs, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UDWORD), , __ARG_A(UDWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, __ARG(UWORD), , __ARG_A(UWORD), __ARG_A(UDWORD), __CNV_SIMPLE, _L_NONE, _TFLG_NONE)
      |      ^~~~~~~~~~~~
../../../include/libc/farptrgs.h:77:6: note: previous declaration of â_farpokew_gsâ with type âvoid(short unsigned int,  long unsigned int,  short unsigned int)â
   77 | void _farpokew_gs(unsigned short, ULONG32, unsigned short);
      |      ^~~~~~~~~~~~
cc1: note: unrecognized command-line option â-Wno-unknown-warning-optionâ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option â-Wno-unneeded-internal-declarationâ may have been intended to silence earlier diagnostics
make[3]: *** [../../makefile.inc:21: thunks_p.o] Fout 1
make[2]: *** [../makefile.lib:9: all] Fout 2
make[1]: *** [makefile:7: subs] Fout 2
make: *** [makefile:58: subs] Fout 2
```

**Comment by stsp** [comment]
And now?

**Comment by jschwartzenberg** [comment]
Continues! Next issue:
```
cc -E -I . -I ../../../../include -DDJ64 -D_IN_DJ64 -CC -g0 -MD fmemcpy.c | \
  sed -E -e 's/^\*\/#/\*\/\n#/' -e 's/^\*\/ *;/\*\/\n;\n/' | \
  cc @../../../gcc.opt  -xc - -c  -o fmemcpy.o
fmemcpy.c: In function ‘get_segment_base_address’:
fmemcpy.c:43:54: error: passing argument 2 of ‘__dpmi_get_segment_base_address’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   43 |     return __dpmi_get_segment_base_address(selector, (unsigned long *)addr);
      |                                                      ^~~~~~~~~~~~~~~~~~~~~
      |                                                      |
      |                                                      long unsigned int *
In file included from fmemcpy.c:32:
../../../../include/dpmi.h:156:70: note: expected ‘unsigned int *’ but argument is of type ‘long unsigned int *’
  156 | int     __dpmi_get_segment_base_address(int _selector, __out ULONG32 *_addr);                   /* DPMI 0.9 AX=0006 */
      |                                                        ~~~~~~~~~~~~~~^~~~~
At top level:
cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-unneeded-internal-declaration’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make[4]: *** [../../../makefile.inc:21: fmemcpy.o] Fout 1
```

**Comment by stsp** [comment]
And now?

**Comment by jschwartzenberg** [comment]
It completed!!
```
$ dj64-gcc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/12/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 12.2.0-14' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=i686-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14)
```

**Comment by stsp** [comment]
Cool, thanks.
